name: Openlake
version: 1.0.0
config-version: 2
profile: Openlake
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  Openlake:
    +materialized: view
